### ISSUE TITLE
DatePickerRange breaks when select first date

### ISSUE THREAD

**Issue by Ajaesuria** [plotly/dash-core-components#480] opened 2019-03-07 12:46 UTC
Good day.

In the current version of dash core components, DatePickerRange throws an error on console when it have been initialized without dates in python and try to open the calendar and the component falls apart.
The error is "currentMonth is undefined".

It feels strange because I have a component built around airbnb/react-dates and it can be initialize without pre-selected dates and when open display actual month, dash core components also takes the same component from there and I'm not saying that my component provides the date somehow. I also tried to copy-paste the entire component from airbnb/react-dates and render and it has no problem with no dates.
In DatePickerSingle is not a problem initialize it without any props or dates only in the Range component.

**Comment by Marc-Andre-Rivet** [comment] 2019-03-07 20:08
@Ajaesuria Thanks for reporting this. Confirming the behavior at least back to dash==0.38.0, probably before.

**Comment by byronz** [comment] 2019-07-29 03:43
@Marc-Andre-Rivet  while verifying #489, I think this issue is not present with the latest code. 
context 
```
dash                 1.0.2
dash-core-components 1.0.0
dash-html-components 1.0.0
dash-renderer        1.0.0
dash-table           4.0.2
```
sample app
```python
import dash_core_components as dcc
import dash_html_components as html
from dash import Dash
from dash.dependencies import Input, Output

app = Dash(__name__)
app.layout = html.Div(
    [
        dcc.DatePickerRange(id='demo')
    ]
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

@Ajaesuria sorry for the late investigation, but if possible could you confirm my verification was correct? thanks

**Comment by Marc-Andre-Rivet** [comment] 2019-08-05 14:57
Tested against `1.0.2`, `0.43.0`, `0.41.0`, `0.37.0` (February 2019) using the code provided by @byronz above and with variations on `start_date` (not defined, None, datetime) and `end_date` (same) and was unable to reproduce the error.

Closing as not reproducible.

@Ajaesuria If you encounter this issue again, don't hesitate to open another issue with the version of the dash packages and a code example to reproduce the issue. Thanks.

**Closed by Marc-Andre-Rivet** 2019-08-05 14:57 UTC
Labels: Stage: Backlog, Type: Bug, size: 1
