### ISSUE TITLE
Can crash Python by trying to print a Checklist with no values

### ISSUE THREAD

**Issue by slishak** [plotly/dash-core-components#231] opened 2018-07-09 13:38 UTC
Printing an empty Checklist crashes my Python interpreter:

```python
import dash_core_components as dcc
c = dcc.Checklist()
print(c)  # crash
```

If I give it an empty `values` argument, it prints fine:
```python
c = dcc.Checklist(values=[])
print(c)  # Checklist(values=[])
```

I'm running Python 3.6.4 with:
```
dash==0.21.1
dash-core-components==0.23.0
dash-html-components==0.11.0
dash-renderer==0.13.0
plotly==3.0.0
```

**Comment by chriddyp** [comment] 2018-07-10 13:15
Duplicate of #133

**Closed by chriddyp** 2018-07-10 13:15 UTC

**Comment by slishak** [comment] 2018-07-10 14:11
Thanks @chriddyp, didn't spot that one. Thought it was interesting that you could crash the whole interpreter by doing this, it doesn't just raise an Exception.
