### ISSUE TITLE
[BUG] Graph(style='height=100%') fails when reducing window size on Firefox

### ISSUE THREAD

**Issue by orenbenkiki** [plotly/dash-core-components#605] opened 2019-08-08 13:11 UTC
**PIP**

```
dash (1.0.2)
dash-bootstrap-components (0.7.0)
dash-core-components (1.0.0)
dash-daq (0.1.7)
dash-html-components (1.0.0)
dash-renderer (1.0.0)
dash-table (4.0.2)
```
**Describe the bug**

Writing: `Graph(..., style=dict(height='100%'))`

**Expected behavior**

The graph should fill the full height of the `div`, which will obey normal CSS rules, that is, span all the available space in the layout. It should not cause any overflow, and respond to window resize (also on Firefox ;-).

**Actual behavior**

* A scrollbar appears for a small amount of overflow (both Chrome and Firefox). Since the amount is small, it is possible to work around this with `overflow=hidden`, but it may cause clipping (e.g. if using long labels for the X axis, etc.).

* Reducing window size does not cause graph resize (Firefox only). That is strange, one would expect that any resize event is handled the same way, regardless if the new size is higher or lower than the original size.

**Edit**

The following example _almost_ works, except for the two issues above. This threw me off, originally I thought that the feature does not work at all. I edited the issue title and content accordingly.

**Comment by alexcjohnson** [comment] 2019-08-16 19:24
Moved the issue to the `dash-core-components` repo where it would be addressed - @antoinerg has some good ideas about how to make this work better 🙏

**Comment by alexcjohnson** [comment] 2019-08-16 19:26
And @orenbenkiki thanks for opening another very clear and helpful issue!

**Comment by wbrgss** [comment] 2019-08-22 21:30
@orenbenkiki I too have experienced some frustrations using Flexbox layouts with `dcc.Graph` — there is more work to be done on complex flex layouts. For your simple example, I think this may work:

```py
...
        dcc.Graph(
            figure=dict(layout=dict(autosize=True)),
            config=dict(responsive=True),
            style={
                'height': '100%',
            },
        ),
```

**Behaviour on Firefox without my suggestion***

![x-axis-cutoff](https://user-images.githubusercontent.com/9068290/63551092-2e5d8c80-c502-11e9-9960-337f2fc1597a.gif)

**With my suggestion (`reponsive=True`)**

![x-axis-visible](https://user-images.githubusercontent.com/9068290/63551099-31587d00-c502-11e9-8c9a-bc0fabf0842b.gif)

That is, add `responsive=True` to the config argument in `dcc.Graph()`. You can thank @antoinerg for that. Related issue plotly/plotly.js#3034 and PR: plotly/plotly.js#3056

Does that solve your problem? The documentation for this could probably be higher-profile, sorry about that. There is a section on it [here](https://plot.ly/javascript/configuration-options/#making-a-responsive-chart).

I also want to echo @alexcjohnson that we appreciate your clear and well-defined issues with examples!

**Comment by orenbenkiki** [comment] 2019-08-25 11:16
Possibly these flags do makes things better, but they don't fix my real-world application. Some computation deep in the code looks at "100%" and interprets it as "100px", causing the (very initial) size to be 100 x 100 pixels, which triggers the "something went wrong with axis scaling" error (when computing the colorbar coordinates). I don't have a minimal program to demonstrate this :-(

**Comment by Marc-Andre-Rivet** [comment] 2019-11-19 21:16
Making my way through the comments made above and will provide feedback as I go through them.

I am using:
- dash==1.6.1 (plotlyjs==1.51.1)
- Chrome 78 / Firefox 70

> A scrollbar appears for a small amount of overflow (both Chrome and Firefox)

This problem is unrelated to the dcc.Graph, while annoying this is normal browser behavior when making a top-level element take 100% of the viewport and is caused by browsers applying a default style to the `body` element.

In Chrome:
```
body {
    display: block;
    margin: 8px;
}
```

Same in Firefox: https://hg.mozilla.org/mozilla-central/file/tip/layout/style/res/html.css#l122

The scrollbar issue can be replicated by simply using an empty div:
```
<div style='display: flex; flex-flow: column; background-color: green; height: 100vh; width: 100vw' />
```

There's really only three ways to handle this:
- explicitly override the body's default margin `margin: 0`
- size the top div by taking the margins into consideration (this won't work in all browsers, as they don't all support mixed units)
```
    height: calc(100vh - 16px);
    width: calc(100vw - 16px);
```
- update Dash's default style to override the browser defaults for body (reset.css) -- IMO we shouldn't do this

> Reducing window size does not cause graph resize (Firefox only)

This seems to be working fine with the versions above. Can you confirm if this behaves better now?

> Although the sample example above sort-of-works, in my real-life application it doesn't :-( I have a complex layout using nested flex boxes

👀 Looking. More to come.

**Comment by Marc-Andre-Rivet** [comment] 2019-11-19 21:42
Using a slightly more complex UI:

<details>
<summary>I could use some help...</summary>
```
import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()
app.layout = html.Div(
    style={
        'display': 'flex',
        'flexFlow': 'column',
        'backgroundColor': 'green',
        'height': 'calc(100vh - 16px)',
        'width': 'calc(100vw - 16px)'
    },
    children=[
        html.Div(
            style={
                'backgroundColor': 'blue',
                'flex': '0 0 100px'
            }
        ),
        html.Div(
            style={
                'backgroundColor': 'red',
                'display': 'flex',
                'flex-direction': 'row',
                'flex': '1'
            },
            children=[
                html.Div(
                    style={
                        'backgroundColor': 'yellow',
                        'flex': '0 0 300px'
                    }
                ),
                html.Div(
                    style={
                        'backgroundColor': 'orange',
                        'flex': '1'
                    },
                    children=[
                        dcc.Graph(
                            figure=dict(layout=dict(autosize=True)),
                            style={
                                'height': '100%',
                                'width': '100%'
                            },
                        ),
                    ]
                )
            ]
        )
    ]
)
app.run_server(debug=True)
```
</details>

**Comment by antoinerg** [comment] 2019-11-19 21:51
> I get a graph that can grow but can't get smaller

That looks a lot like this plotly.js issue https://github.com/plotly/plotly.js/issues/3034 which was fixed by https://github.com/plotly/plotly.js/pull/3056 . What happens when you turn on the configuration option `{responsive: true}` on the plotly.js figure?

**Comment by Marc-Andre-Rivet** [comment] 2019-11-19 21:52
@antoinerg Too fast! I updated the comment above with `responsive=True` 😀

**Comment by antoinerg** [comment] 2019-11-19 22:04
@Marc-Andre-Rivet By setting `responsive=True`, plotly.js will change the CSS of the div it draws into as detailed in https://github.com/plotly/plotly.js/pull/3056 . This is necessary to make sure it behaves properly in `flex` and `grid`.

However, as of right now, with `responsive=True`, plotly.js will also add event handlers to the page and trigger the resize operations itself. I think those handlers are unwanted in the context of Dash. Dash should triger the resize operations and check whether they are all finished before considering the page to be fully loaded and ready to say be printed to PDF.

**Comment by Marc-Andre-Rivet** [comment] 2019-11-20 15:33
Testing this out with a more complex scenario where the elements themselves can be resized without the window being resized. The graph does not react to these changes.

```
import dash
from dash.exceptions import PreventUpdate
from dash.dependencies import Input, Output, State

import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()
app.layout = html.Div(
    style={
        'display': 'flex',
        'flexFlow': 'column',
        'backgroundColor': 'green',
        'height': 'calc(100vh - 16px)',
        'width': 'calc(100vw - 16px)'
    },
    children=[
        html.Div(
            style={
                'backgroundColor': 'blue',
                'flex': '0 0 100px'
            },
            children=[
                html.Button(
                    id='resize',
                    children=['Resize']
                )
            ]
        ),
        html.Div(
            style={
                'backgroundColor': 'red',
                'display': 'flex',
                'flex-direction': 'row',
                'flex': '1'
            },
            children=[
                html.Div(
                    id='menu',
                    style={
                        'backgroundColor': 'yellow',
                        'flex': '0 0 300px'
                    }
                ),
                html.Div(
                    style={
                        'backgroundColor': 'orange',
                        'flex': '1'
                    },
                    children=[
                        dcc.Graph(
                            figure=dict(layout=dict(autosize=True)),
                            config=dict(responsive=True),
                            style={
                                'height': '100%',
                                'width': '100%'
                            },
                        ),
                    ]
                )
            ]
        )
    ]
)

@app.callback(
    Output('menu', 'style'),
    [Input('resize', 'n_clicks')]
)
def resizeContainer(n_clicks):
    if n_clicks is None:
        raise PreventUpdate

    width = (n_clicks % 3) * 300 + 300
    color = 'yellow' if n_clicks % 2 == 0 else 'pink'

    return {
        'backgroundColor': color,
        'flex': '0 0 {}px'.format(width)
    }


app.run_server(debug=True)
```

**Comment by Marc-Andre-Rivet** [comment] 2019-11-20 18:48
Documenting some historic issues / pr / links related to the work.

https://github.com/plotly/plotly.js/pull/2974/files
https://github.com/plotly/plotly.js/pull/3056/files
https://github.com/plotly/orca/blob/8a90d446b73f25da9ad7c7bbdb49b91bec9e7573/src/component/plotly-dash-preview/render.js#L40-L69
https://community.plot.ly/t/cant-seem-to-change-default-height-on-graph/6742

**Comment by Marc-Andre-Rivet** [comment] 2019-11-20 19:33
Trying out the following strategy:

* `autosize: true` + `responsive: false` applied by default to `dcc.Graph` -- allows for Plotly.js to be ready for resize events but prevents it from resizing on its own (Dash controls the flow)
* ResizeObserver / polyfill https://github.com/maslianok/react-resize-detector to trigger `Plotly.Plots.resize(target)`
* state driven `is-resizing` or `is-ready` class on graph to determine if the graph is ready or in the process of resizing itself -- useful for both tests and usages dependent on the resize/redraw state

**Comment by wbrgss** [comment] 2019-11-20 20:20
@Marc-Andre-Rivet @antoinerg 

Got a demo for you guys, hopefully this will help understand the problem, or at least otherwise educate me on what I'm doing wrong. I'm demonstrating with three ways of describing the figure — `px`, `plotly.graph_objs`, and using a dict. I also include a callback to demonstrate how using `style={'height': 'inherit'}` will still fail when setting a `figure` via a callback — setting the figure directly as an argument to `dcc.Graph` appears to work.

dash ==1.6.1
plotly==4.3.0

```py
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import plotly.graph_objs as go

from dash.dependencies import Input, Output, State, ClientsideFunction

app = dash.Dash(__name__)
server = app.server

iris = px.data.iris()

div_style = {
    # for visual demonstration
    'padding': '10px',
    'background-color': 'red',
    # the key style argument - constrained height containers
    'height': '400px'
}

app.layout = html.Div(children=[

    html.Div(style=div_style,
        children=[
            dcc.Graph(
                figure={
                    'data': [{
                        'x': [1, 2, 3, 4],
                        'y': [5, 4, 3, 6],
                        'line': {'shape': 'spline'}
                    }],
                    'layout': {'autosize': True},
                },
                config={'responsive': True},
            )
        ]
    ),

    html.Div(style={'height': '200px'}),

    html.Div(style=div_style,
        children=[
            dcc.Dropdown(
                id='flower-dropdown',
                options=[
                    {'label': i, 'value': i} for i in
                    ['Sepal', 'Petal']
                ],
                value='Sepal',
            ),
            dcc.Graph(id='flower-graph',
                # will not even respond to 'height': 'inherit'
                # *when the figure is returned by a callback*

                # not sure if this is px or the callback or both
                config={'responsive': True},
                style={'height': 'inherit'}
            )
        ]
    ),

    html.Div(style={'height': '500px'}),

    html.Div(style=div_style,
        children=[
            dcc.Graph(
                figure={
                    'data': [
                        go.Scatter(
                            x=[1, 2, 3, 4, 5],
                            y=[4, 3, 1, 5, 1],
                            line=go.scatter.Line(shape='spline')
                        )
                    ],
                    'layout': {'autosize': True},
                },
                config={'responsive': True},
                # this will make the graph respond appropriately
                # remove the style argument, and the graph will
                # overflow, despite the 'responsive' flag being set
                style={'height': 'inherit'}
            )
        ]
    ),

    # style arguments for visual demonstration, no affect on graph dimensions
], style={'background-color': 'green', 'height': '300vh'})


@app.callback(
    Output('flower-graph', 'figure'),
    [Input('flower-dropdown', 'value')])
def update_output(val):
    if val == 'Petal':
        x_val = "petal_width"
        y_val = "petal_length"
    else:
        x_val = "sepal_width"
        y_val = "sepal_length"

    fig=px.scatter(iris,
        x=x_val,
        y=y_val,
        color="species")

    fig.update_layout(autosize=True)

    return fig

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by wbrgss** [comment] 2019-11-20 20:24
The third example works, but take note of my comments on the style argument — commenting it out will   make the graph overflow.

**Comment by Marc-Andre-Rivet** [comment] 2019-11-21 22:02
@wbrgss Using the code currently in (early) review https://github.com/plotly/dash-core-components/pull/706

For this to work and the graph to be bounded to its container, it needs to be styled appropriately. The 1st graph needs
```
responsive=True,
style=dict(height='100%', width='100%')
```

The 2nd graph needs some way to divide the space between itself and the dropdown, this can be achieved for example by adding to the container's style
```
dict(dict(display='flex', flexDirection='column'), **div_style)
```

**Closed** 2019-12-16 23:47 UTC
Labels: Meta: Prioritized, Stage: In Review, Type: Bug

**Comment by soerendip** [comment] 2020-06-02 01:29
It is not yet working for python right?
