### ISSUE TITLE
dcc.Link - links should still work if the href isn't relative

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-core-components#775] opened 2020-03-12 06:15 UTC
i.e. this should work:
```
dcc.Link(href='https://google.com')
```

to start, we could just force that non-relative links start with `https://` and `http://`.

cc @plotly/dash-core

**Comment by Marc-Andre-Rivet** [comment] 2020-03-16 14:54
Closing as duplicate of https://github.com/plotly/dash-core-components/issues/771

**Closed by Marc-Andre-Rivet** 2020-03-16 14:54 UTC
